### ISSUE TITLE
Install the plugin using a zip file from my local machine

### ISSUE THREAD

**Issue by royboy789** [cloudsponge/better-sharing-wp#1]
Installation should include the proxy URL.

https://www.cloudsponge.com/developer/oauth/proxy-url/

**Comment by royboy789** [comment]
To create a release (that can be used as a zip), we will need to

- Create a new release branch, something like `release-1.0.0`
- Remove build files from `.gitignore`
- Build and add build files to branch, and commit to remote (GitHub)
- Create a new release, based on branch, with version number
- Save zipped file for other locations, or for others to download and use.

**Comment by royboy789** [comment]
We can probably automate this into a script as well.

**Comment by circuitfive** [comment]
I think we can close this one for now and just focus on deploying to wordpress.org repo.

**Comment by circuitfive** [comment]
I think we can close this one for now and just focus on deploying to wordpress.org repo, right @royboy789?
