### ISSUE TITLE
Resolve Netlive.live bug

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#13]
The AutomateWoo add-on doesn't appear in the front end for all users.

Viewing that same page with Roy's account seems to work properly.

**Comment by royboy789** [comment]
no updates on this - had sent a few emails out asking for more data / credentials.

**Comment by royboy789** [comment]
Email update sent with potential fix to their issue.
Previous issue of separate view per user fixed, determined it could have been a http/s issue.
