### ISSUE TITLE
Create auto-updater

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#14]
Let's make sure that when we create a new release in Github all of our customers get the notification in their WordPress administrator panels letting them download the new version.

Here's an idea for how to do it.. https://www.smashingmagazine.com/2015/08/deploy-wordpress-plugins-with-github-using-transients/

**Comment by royboy789** [comment]
Talking to Andy Fragen of [GitHub Updater](https://github.com/afragen/github-updater) to see if this can be done without the user(s) seeing that plugin. Pretty sure this is doable, but will want to confirm before moving forward.

The tutorial you posted is good, except rather not maintain this extensive of functionality if possible.

**Comment by circuitfive** [comment]
We don't need this since this plugin will only ever be in the wordpress.org repository and it'll use WordPress's built in updater functionality.
