### ISSUE TITLE
Create a deployment process to WordPress.org SVN

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#15]
Once a new release is created, let's figure out how we're going to ship it to WordPress.org.

We might wants a separate repo for this deployment script so that we don't have to mess around with making sure it doesn't get bundled with the plugin code.

**Comment by royboy789** [comment]
we would need to remove GitHub Updater, or any other GitHub auto updating libraries. 

Another branch would be best, that way updates can be merged in. MAYBE a separate repo? but don't think that will be necessary

**Comment by royboy789** [comment]
https://wordpress.org/plugins/developers/add/

**Comment by royboy789** [comment]
I need to verify this works by testing it, but looking at this deploy script:
https://ericbusch.net/deploy-your-plugin-to-the-wordpress-org-svn-plugin-repository-from-your-github-repository

https://gist.github.com/EricBusch/58c6e9bbc122d52507ed971066d14336

**Comment by royboy789** [comment]
## Objective ##
A single CI command should:
- [ ] Ask for version number
- [ ] (Optional) Modify `readme.txt` and `BetterSharingWP` <- 2 locations
- [ ] Create new branch based off master with version (build-v[version])
- [ ] Modify gitignore as needed
- [ ] Trigger build scripts
- [ ] Create release in git with build
- [ ] Move build directory to a new directory, `new loc: tmp-build/build`
- [ ] Copy all php and other asset files into `tmp-build`
- [ ] Run deploy script (see previous comment), modified as needed with `tmp-build` as the plugin base
- [ ] Create a zip of `tmp-build`
- [ ] Delete `tmp-build`

The reasoning for this setup is the deploy script from above is based on a fully built plugin (no js concatenation, no external libraries, etc.)

**Comment by royboy789** [comment]
Releases for GitHub cannot be created via git and pushed to GitHub. I will create a tag, and use the branch to build the release manually.

**Comment by royboy789** [comment]
For Friday 7/14 - have a temp zip ready for org repo submission

**Comment by royboy789** [comment]
here is the branch with the most up to date code / build script:
https://github.com/cloudsponge/better-sharing-wp/tree/plugin-package

**Comment by circuitfive** [comment]
Related to #29

**Comment by royboy789** [comment]
PR #39 - includes latest build commands and all code after preliminary testing on zip-test multidev
#36 - Marketing material.

**Comment by royboy789** [comment]
This is completed with the build command `npm run build:plugin`
