### ISSUE TITLE
Design the logo that we're going to use

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#16]
We already have an Asana thread for this: https://app.asana.com/0/918130373782990/1171433759266441

@dimitarangelkov please watch the video I shared in Asana and see what you can do.

**Comment by dimitarangelkov** [comment]
### Simplified rocket
![8-big](https://user-images.githubusercontent.com/14825668/84243732-4ba02d80-ab0b-11ea-8f1e-1ed07cb30591.png)

![preview8-search](https://user-images.githubusercontent.com/14825668/84243758-58248600-ab0b-11ea-8a04-6e63d2aedae4.png)

![preview8](https://user-images.githubusercontent.com/14825668/84243797-6377b180-ab0b-11ea-8141-3ab9b6e43674.png)

### A bit more detailed rocket

![7-big](https://user-images.githubusercontent.com/14825668/84243899-8d30d880-ab0b-11ea-8f3a-5fb45f1dd844.png)

![preview7-search](https://user-images.githubusercontent.com/14825668/84243907-928e2300-ab0b-11ea-8f62-7bebd49a955f.png)

![preview7](https://user-images.githubusercontent.com/14825668/84243931-9d48b800-ab0b-11ea-8d23-146c016a22bd.png)

**Comment by circuitfive** [comment]
Test comment for Diego!

**Comment by dimitarangelkov** [comment]
@circuitfive proportions visualisation for the logo, with two variants for the rocket top.

![better-sharing](https://user-images.githubusercontent.com/14825668/85747812-48fb2600-b710-11ea-89bb-d2712cdd6317.png)

**Comment by circuitfive** [comment]
Did you make any changes to icon-1 @dimitarangelkov? It looks the same to me.

I don't like icon-2.

**Comment by dimitarangelkov** [comment]
No changes to icon-1, as you requested we just added the proportions so you can see how the elements correspond to each other. 
icon-2 is a different variant, with different alignment of the rocket elements to the rest of the icon objects.

**Comment by circuitfive** [comment]
Ok, I will try to be more clear this time. I want to see a new design, similar to icon-1, that is entirely based on the proportions and measurements of the original icon rather than arbitrary measurements.

The bottom line is that icon-1 is very close, but I think it will be perfect if we take this step.

I will use some kind of rudimentary technique, probably pencil and paper, to show you what I mean and add it to this issue.

**Comment by circuitfive** [comment]
Here's a video describing what I want in more detail... https://www.loom.com/share/0d8d3529b42f4afa95fd99a5140673f8

![better-sharing-icon-concept-03-sketch](https://user-images.githubusercontent.com/2659746/85791716-286aa600-b6e7-11ea-9f36-e114dd3acdaf.jpg)

![better-sharing-icon-concept-03-mockup](https://user-images.githubusercontent.com/2659746/85791735-2f91b400-b6e7-11ea-9cbc-51cd5735680a.jpg)

**Comment by circuitfive** [comment]
Another fun exercise in Euclidian geometry, finding the center of the big circle. Mainly just saving it here because it'll be fun to look back at it someday.

![better-sharing-icon-concept-circles](https://user-images.githubusercontent.com/2659746/85803208-80130c80-b6fb-11ea-8490-90d8b6e2f01d.jpg)

**Comment by dimitarangelkov** [comment]
@circuitfive 

![all](https://user-images.githubusercontent.com/14825668/87155784-3eba5980-c2c4-11ea-9027-6c5692b26e12.png)

And here is the Black & White logo

![1024](https://user-images.githubusercontent.com/14825668/87155889-6d383480-c2c4-11ea-8953-d9a4a212e723.png)

**Comment by circuitfive** [comment]
@dimitarangelkov It looks like there's a flat edge at the bottom of the tail, I guess maybe that'll go away when we make this a vector?

Please don't forget to put the source files for this into our shared Google Drive folder along with all everything else. Every illustration you've ever done for CloudSponge should always have its source file(s) organized in this folder. All of them.

**Comment by dimitarangelkov** [comment]
source uploaded to Google Drive

**Comment by dimitarangelkov** [comment]
![1024](https://user-images.githubusercontent.com/14825668/94273522-354c9f00-ff4d-11ea-8b44-f272699354bd.png)
