### ISSUE TITLE
Need assets for plugin

### ISSUE THREAD

**Issue by royboy789** [cloudsponge/better-sharing-wp#18]
Image Asset Docs:
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#default-image-sizes

Needed:

- [ ] banner-772x250.png
- [ ] icon-256x256.png

**Comment by dimitarangelkov** [comment]
@circuitfive 
**Banner 772x250**
![banner-772x250](https://user-images.githubusercontent.com/14825668/93567381-3acb4780-f997-11ea-9fd4-8b0ec898de65.png)

**Icons 256x256**
Color
![icon-256x256-color](https://user-images.githubusercontent.com/14825668/93567391-3e5ece80-f997-11ea-9632-48fba95a6088.png)
BW
![icon-256x256](https://user-images.githubusercontent.com/14825668/93567412-44ed4600-f997-11ea-8893-397a3dba323d.png)

Source uploaded to Google Drive.

**Comment by circuitfive** [comment]
@dimitarangelkov 

## Banner
Can we please try a design that matches the rest of CloudSponge? I don't think we need to invent anything new here, just use things from the existing library like our hero background, fonts, colors, styles, etc. No need to do something completely new.

## Icon
The flat part at the bottom of the tail is still there, please fix it and resubmit.

**Comment by circuitfive** [comment]
Also, the banner doesn't need a different rocket, just keep it simple and use the icon we created on the banner please.

**Comment by dimitarangelkov** [comment]
@circuitfive 

![banner-772x250](https://user-images.githubusercontent.com/14825668/94273617-4eede680-ff4d-11ea-8e3b-243e8aa4d913.png)

![icon-256x256-color](https://user-images.githubusercontent.com/14825668/94273641-56ad8b00-ff4d-11ea-9dc4-3ab5c7cab8d8.png)

![icon-256x256](https://user-images.githubusercontent.com/14825668/94273674-6036f300-ff4d-11ea-9412-76eaada0c815.png)

**Comment by dangerouse** [comment]
:+1:

**Comment by dimitarangelkov** [comment]
![banner-772x250](https://user-images.githubusercontent.com/14825668/108598818-a8413100-7398-11eb-91d2-2d2c847dc632.png)

![icon-256x256](https://user-images.githubusercontent.com/14825668/108598820-ad05e500-7398-11eb-9686-ce95f95ef92a.png)

![logo-final](https://user-images.githubusercontent.com/14825668/108599272-eb030900-7398-11eb-95df-feb26fa51883.png)
