### ISSUE TITLE
Create AutomateWoo Refer-a-Friend demo

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#22]
This should be in a multidev branch of the demo sandbox in Pantheon.

**Comment by circuitfive** [comment]
Related to #8

**Comment by dimitarangelkov** [comment]
This is the demo URL
https://automatewoo-better-sharing-demo.pantheonsite.io/
https://automatewoo-better-sharing-demo.pantheonsite.io/wp-admin/

The add-on installation is still in progress. Will post an update when ready.

**Comment by royboy789** [comment]
https://demo-auto-better-sharing-demo.pantheonsite.io/referral-page/
