### ISSUE TITLE
Create a Gutenberg block for default email sharing functionality

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#30]
It should look like this:

![image (2).png](https://images.zenhubusercontent.com/5893c7ec51aa2c3057736077/acd18f47-96e4-44e5-b754-a03c59d5bf42)

The "Add From Contacts" button isn't displayed unless a CloudSponge key is present.

The "Send Email" functionality is using the default WP outbound email settings.

**Comment by royboy789** [comment]
- Gutenberg Block
- Setting to turn "on" as sharing on any post/page below content

**Comment by circuitfive** [comment]
To truly earn the moniker "Better Sharing" the core functionality would have to include three basic features:

1. Copy link to clipboard. So that the user can share the link wherever they want.
1. Send emails. So the user can spread the word to people via email. In this case CloudSponge's Contact Picker would only be enabled if we have a CloudSponge key. Otherwise the users will just have to type email addresses manually.
1. Share on social media. Pre-loaded tweets/posts/etc for each social network we decide to support.

Here's Morning Brew's interface for reference since we're basically just copying it.

![image](https://user-images.githubusercontent.com/2659746/98043505-2d004300-1dda-11eb-87b1-ba38df76f75d.png)

**Comment by terminusagency** [comment]
For the share via email portion, I would envision that setting the email body could be as simple as having an html field in the plugin settings for "Share Via Email" and the field would accept HTML text.  That would automatically be pulled into the body like in the example above.  Is the address "from" set in the settings?

In a more advanced development stage, it would be super cool if the plugin created a custom post type for Share Via Email and you could embed via a shortcode, something like [better-share id="1"] and each post with the custom post type gives a unique shortcode.  If you need an example Caldera forms does this with their forms.

**Comment by royboy789** [comment]
Hey @terminusagency 
I'll be putting time into this during this week. 

Just to clear this up on the scope of the core functionality

## Scope
Overview: A better way to share a referral link, or any other piece of text

### Features
- [ ] Editor Block or Shortcode that outputs a shareable link email form & social sharing buttons
- [ ] Emails to be sent via default WP way (this is already customizable by other plugins)
- [ ] Link (or any customizable "share content") has copy to clipboard button
- [ ] Email message to be either customizable by user, a readonly or no hidden
- [ ] Input field to accept CSV style emails (email@one.com,email@two.com)
- [ ] If CloudSponge API is hooked up, add the "Add from Contacts" Button
- [ ] Customizable messaging per social platform
- [ ] All appropriate text input or textarea to accept a {{link}} variable to output the link

### Block / Shortcode Configurations
- [ ] Share link (assuming based on some other data - **needs discovery**)
- [ ] Email Message: Hide | Read Only | Customizable
- [ ] Email Message WYSIWYG
- [ ] Social Network Toggles (if they show or not)
- [ ] Social Network Messages (One for each active)

## Questions
@circuitfive  & @terminusagency - remaining questions and brainstorming
- Share Link - how are we customizing this per user, should that be part of of this plugin?
- Social Sharing - thoughts here on using ShareThis or some other sharing library to power this? Most offer custom messaging. I'd have to do a bit of discovery if you can use ShareThis without an account / api access
- Do you think a better place for this configuration is at the block level. Or do you think having it in a global place is better. Think of this as setting up a "campaign" and then each block can be that configuration. The only benefit here is if you envision 1 type of form showing up in multiple places vs. each form being customizable (you can also use the editor to save blocks as stored blocks)

**Comment by circuitfive** [comment]
> Share Link - how are we customizing this per user, should that be part of this plugin?

I think it's the URL to the current page's permalink. We could optionally allow the WP administrator to override this default, but I'd call that a stretch goal for v1.

> Social Sharing - thoughts here on using ShareThis or some other sharing library to power this? Most offer custom messaging. I'd have to do a bit of discovery if you can use ShareThis without an account / api access

I think we should do direct integrations here so that we don't add another dependency to an already complicated stack of plugins and addons. Let's just start with [Twitter's "Share Button"](https://publish.twitter.com/?buttonType=TweetButton&widget=Button) and [Facebook's "Share Button"](https://developers.facebook.com/docs/plugins/share-button/#) to keep the scope confined for now.

> Do you think a better place for this configuration is at the block level. Or do you think having it in a global place is better. Think of this as setting up a "campaign" and then each block can be that configuration. The only benefit here is if you envision 1 type of form showing up in multiple places vs. each form being customizable (you can also use the editor to save blocks as stored blocks)

I don't have an opinion on this. I think @terminusagency will have a good suggestion.

**Comment by terminusagency** [comment]
Agree with @circuitfive  that an integration with Share This creates added timeline and complexity in the short term, BUT I don't know if Facebook allows integration without grabbing an APP ID somehow from their developers console.  It could be input into a dashboard field. Perhaps it only shows Facebook option if an APP ID has been added? Forgive if my understanding is off.

Would a direct to Facebook share integration require an App ID?  https://developers.facebook.com/docs/plugins/share-button/

It looks like Twitter allows you to pass info in a link easily: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by royboy789** [comment]
@terminusagency we are wrapping up the MVP feature set that is described here in what I think will be a release shortly.

Wanted to see if you'd be interested to test it out and give feedback. This includes a Gutenberg block for the featureset. We were debating internally to add a shortcode as a fallback, but haven't yet. 

We don't have documentation, so hopefully it is easy enough, and if not, we'll have to think about how to fix or document through it.

Thank You!

**Comment by dangerouse** [comment]
Add the shortcode.

**Comment by terminusagency** [comment]
I do agree with Graeme, a shortcode will be extremely useful for anyone
who's not using the Gutenberg block editor for page layouts.

**Comment by circuitfive** [comment]
@royboy789 I tried making a zip for @terminusagency to test please take a peek and let me know if it looks right: https://drive.google.com/file/d/1brRl3QF32OfUwiYpQQqHQRmPX60Z6cGa/view?usp=sharing

**Comment by circuitfive** [comment]
@bszyk @royboy789 jump to 2:16 in this video to see broken behavior with sending emails: https://www.loom.com/share/5fac0d2172e14bd3b4b9e06352ce5a10

Thank you @terminusagency

**Comment by royboy789** [comment]
This was completed. Lets create new tickets for any outstanding issues with `1.3.6`

**Comment by bszyk** [comment]
in progress
