### ISSUE TITLE
Create basic marketing material

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#36]
Two primary places for this for now...

1. The `readme.txt` that's included with the plugin that ends up becoming its landing page on wordpress.org
1. A lander on cloudsponge.com/better-sharing/wordpress/

Each one should have some basic copy about what the plugin does plus a collection (CPTs?) of addons with before-and-after pictures and bullet points of the functionality that we're providing with each.

@dimitarangelkov let's use this thread to get you all the answers you need to create these assets.

**Comment by royboy789** [comment]
Current readme:

`
=== Plugin Name ===
Contributors: cloudsponge
Tags: sharing, cloud, address book
Requires at least: 5.0
Tested up to: 5.5.3
Requires PHP: 7.4
Stable tag: 1.1.0
License: GPLv3 or later
License URI: http://www.gnu.org/licenses/gpl-3.0.html
 
Better Sharing WordPress plugin for use for CloudSponge
`

**Comment by royboy789** [comment]
@circuitfive @dimitarangelkov Not sure if assets have been made:

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

## Banner
```
    Normal Banner: banner-772x250.(jpg|png)
    Normal Banner (RTL): banner-772x250-rtl.(jpg|png)
    High-DPI (Retina): banner-1544x500.(jpg|png)
    High-DPI (Retina RTL): banner-1544x500-rtl.(jpg|png)
````

## Icons
```
    Normal: icon-128x128.(png|jpg)
    High-DPI (Retina): icon-256x256.(png|jpg)
    SVG: icon.svg
```

# Screenshots
```
screenshot-1.(png|jpg)
screenshot-2.(png|jpg)
```
I'll need to add text in the `readme.txt` file when those are created so they show up.

**Comment by royboy789** [comment]
For @royboy789 :
- [ ] Add Screenshots to Readme

**Comment by dimitarangelkov** [comment]
I've updated the formatting a bit. This is the maximum without changing the template. Will prepare enhanced version of the template sometime next week.
https://www.cloudsponge.com/better-sharing/

**Comment by circuitfive** [comment]
@royboy789 we kept this branch so that you could move these assets to the correct place whenever you're ready:

https://github.com/cloudsponge/better-sharing-wp/tree/add-assets

Once you've got them where they're supposed to go, you can delete that branch.

**Comment by dimitarangelkov** [comment]
@royboy789 assets updated https://github.com/cloudsponge/better-sharing-wp/tree/add-assets
