### ISSUE TITLE
change megaphone icon to our custom monochrome icon

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#44]
https://github.com/cloudsponge/better-sharing-wp/blob/efd3e5b3e06756dfee59130da2c785b1eabc01a4/includes/Admin.php#L38

This one: https://github.com/cloudsponge/better-sharing-wp/issues/16#issuecomment-698932601

@royboy789 please share any best practices or advice for the right way to do this.

**Comment by royboy789** [comment]
@circuitfive can you get me the svg data string?
```
Pass a base64-encoded SVG using a data URI, which will be colored to match the color scheme. This should begin with 'data:image/svg+xml;base64,'. 
```

**Comment by dimitarangelkov** [comment]
@royboy789 here it is

`data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHZpZXdCb3g9IjAgMCAyMCAyMCI+DQogIDxkZWZzPg0KICAgIDxjbGlwUGF0aCBpZD0iY2xpcC1fMjAiPg0KICAgICAgPHJlY3Qgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIi8+DQogICAgPC9jbGlwUGF0aD4NCiAgPC9kZWZzPg0KICA8ZyBpZD0iXzIwIiBkYXRhLW5hbWU9IjIwIiBjbGlwLXBhdGg9InVybCgjY2xpcC1fMjApIj4NCiAgICA8cmVjdCB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIGZpbGw9InJnYmEoMjU1LDI1NSwyNTUsMCkiLz4NCiAgICA8ZyBpZD0iQ29tcG9uZW50XzJfNCIgZGF0YS1uYW1lPSJDb21wb25lbnQgMiDigJMgNCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMSkiPg0KICAgICAgPHBhdGggaWQ9IlBhdGhfNDgiIGRhdGEtbmFtZT0iUGF0aCA0OCIgZD0iTTYxMi42OSw1NS4xNzNWNTQuNzZhMi4wNjgsMi4wNjgsMCwwLDAtMS40LTEuOTU2bC0uNjY4LS44LS42NjguOGEyLjA2OCwyLjA2OCwwLDAsMC0xLjQsMS45NTZ2LjQxNGwtMS4zNzksMS42NTVoMS4zNzl2MS4zNzloNC4xMzhWNTYuODI5aDEuMzc5Wm0tMi4wNjkuMjc2YS42OS42OSwwLDEsMSwuNjktLjY5aDBBLjY5LjY5LDAsMCwxLDYxMC42MjEsNTUuNDQ5WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTU5Ni4xMzggLTUyLjAwMSkiLz4NCiAgICAgIDxwYXRoIGlkPSJQYXRoXzQ5IiBkYXRhLW5hbWU9IlBhdGggNDkiIGQ9Ik02MjguOTEyLDM2OS4yMzlhMTIuMjc4LDEyLjI3OCwwLDAsMS0yLjMxNiw2LjY1Myw4LjQ2Nyw4LjQ2NywwLDAsMCwzLjY5LTYuNjUzWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTYxNS4xMzkgLTM2Mi4zNDMpIi8+DQogICAgICA8cGF0aCBpZD0iUGF0aF81MCIgZGF0YS1uYW1lPSJQYXRoIDUwIiBkPSJNMzAxLjQ2LDM2OS4yMzljLS4yNjYsNC4wNi0yLjg1Niw3LjM0Ni02LjE5NSw3Ljk4OGExMS4yMTYsMTEuMjE2LDAsMCwwLDMuNzg2LTcuOTg4aC0uODY2Yy0uMyw1LjAxLTMuODgxLDguOTY2LTguMjUzLDguOTY2YTE2LjY2OSwxNi42NjksMCwwLDAsNS4xNDUsMGMzLjk4LS42NjksNi45NDItMy45NTUsNy4yNDYtOC45NjZaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjg1Ljc5NCAtMzYyLjM0MykiLz4NCiAgICAgIDxwYXRoIGlkPSJQYXRoXzUxIiBkYXRhLW5hbWU9IlBhdGggNTEiIGQ9Ik0xMTQuNzU5LDIyMC42NjhWMjI1LjFhLjY5LjY5LDAsMCwxLS42ODkuNjlIMTAxLjY1NmEuNjkuNjksMCwwLDEtLjY5LS42OVYyMTIuNjg4YS42OS42OSwwLDAsMSwuNjktLjY5aDcuNjA4bDEuMTQ5LTEuMzc5aC05LjQ0N0ExLjM3OSwxLjM3OSwwLDAsMCw5OS41ODcsMjEydjEzLjc5M2ExLjM3OSwxLjM3OSwwLDAsMCwxLjM3OSwxLjM3OWgxMy43OTNhMS4zNzksMS4zNzksMCwwLDAsMS4zNzktMS4zNzloMHYtNy40NDJBMTEuMDg5LDExLjA4OSwwLDAsMSwxMTQuNzU5LDIyMC42NjhaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtOTkuNTg3IC0yMDcuMTcxKSIvPg0KICAgIDwvZz4NCiAgPC9nPg0KPC9zdmc+DQo=`

**Comment by royboy789** [comment]
thank you @dimitarangelkov

**Comment by royboy789** [comment]
pushed this in commit 0df31df1c9be21593811f74f5e668a1c1fb7eb78 to `feature/core-block` 
Here is an example.

![Screen Shot 2020-12-18 at 7 06 19 AM](https://user-images.githubusercontent.com/4039786/102612951-ab514400-40ff-11eb-9d58-7626324ffbb8.png)


@circuitfive / @dimitarangelkov let me know if this looks good to you and I can close this issue out.

**Comment by dimitarangelkov** [comment]
try this one

`data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMThweCIgaGVpZ2h0PSIyMHB4IiB2aWV3Qm94PSIwIDAgMTggMjAiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8dGl0bGU+Q29tcG9uZW50XzJfNDwvdGl0bGU+CiAgICA8ZyBpZD0iUGFnZS0xIiBzdHJva2U9Im5vbmUiIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8ZyBpZD0iMjAiIGZpbGw9IiNGRkZGRkYiIGZpbGwtcnVsZT0ibm9uemVybyI+CiAgICAgICAgICAgIDxnIGlkPSJDb21wb25lbnRfMl80Ij4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xNi41NTIsMy4xNzIgTDE2LjU1MiwyLjc1OSBDMTYuNTUxNTEyMiwxLjg3NDc0MDQgMTUuOTg4ODU3MywxLjA4ODYzMTE1IDE1LjE1MiwwLjgwMyBMMTQuNDg0LDAuMDAzIEwxMy44MTYsMC44MDMgQzEyLjk3OTE0MjcsMS4wODg2MzExNSAxMi40MTY0ODc4LDEuODc0NzQwNCAxMi40MTYsMi43NTkgTDEyLjQxNiwzLjE3MyBMMTEuMDM3LDQuODI4IEwxMi40MTYsNC44MjggTDEyLjQxNiw2LjIwNyBMMTYuNTU0LDYuMjA3IEwxNi41NTQsNC44MjggTDE3LjkzMyw0LjgyOCBMMTYuNTUyLDMuMTcyIFogTTE0LjQ4MywzLjQ0OCBDMTQuMTAxOTIzNSwzLjQ0OCAxMy43OTMsMy4xMzkwNzY0OCAxMy43OTMsMi43NTggQzEzLjc5MywyLjM3NjkyMzUyIDE0LjEwMTkyMzUsMi4wNjggMTQuNDgzLDIuMDY4IEMxNC44NjQwNzY1LDIuMDY4IDE1LjE3MywyLjM3NjkyMzUyIDE1LjE3MywyLjc1OCBMMTUuMTczLDIuNzU4IEMxNS4xNzMsMi45NDA5OTkzOCAxNS4xMDAzMDM4LDMuMTE2NTAzNTggMTQuOTcwOTAzNywzLjI0NTkwMzY4IEMxNC44NDE1MDM2LDMuMzc1MzAzNzggMTQuNjY1OTk5NCwzLjQ0OCAxNC40ODMsMy40NDggTDE0LjQ4MywzLjQ0OCBaIiBpZD0iUGF0aF80OCI+PC9wYXRoPgogICAgICAgICAgICAgICAgPHBhdGggZD0iTTEzLjc3Myw2Ljg5NiBDMTMuNjY3NDMyLDkuMjkyMjgzMiAxMi44NjIyODU4LDExLjYwNTE2NjMgMTEuNDU3LDEzLjU0OSBDMTMuNjcwMTU1MywxMi4wMzk4OTIyIDE1LjAzODY1NDgsOS41NzI1MTM0IDE1LjE0Nyw2Ljg5NiBMMTMuNzczLDYuODk2IFoiIGlkPSJQYXRoXzQ5Ij48L3BhdGg+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMTUuNjY2LDYuODk2IEMxNS40LDEwLjk1NiAxMi44MSwxNC4yNDIgOS40NzEsMTQuODg0IEMxMS43NzMzMDkyLDEyLjg1MTg5NDIgMTMuMTQxNzM2MSw5Ljk2NDY3OTggMTMuMjU3LDYuODk2IEwxMi4zOTEsNi44OTYgQzEyLjA5MSwxMS45MDYgOC41MSwxNS44NjIgNC4xMzgsMTUuODYyIEM1Ljg0MjY2NDkxLDE2LjEyODI2ODIgNy41NzgzMzUwOSwxNi4xMjgyNjgyIDkuMjgzLDE1Ljg2MiBDMTMuMjYzLDE1LjE5MyAxNi4yMjUsMTEuOTA3IDE2LjUyOSw2Ljg5NiBMMTUuNjY2LDYuODk2IFoiIGlkPSJQYXRoXzUwIj48L3BhdGg+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMTUuMTcyLDEzLjQ5NyBMMTUuMTcyLDE3LjkyOSBDMTUuMTcyMDAwNCwxOC4zMDk2ODYzIDE0Ljg2MzY4NTksMTguNjE4NDQ4MyAxNC40ODMsMTguNjE5IEwyLjA2OSwxOC42MTkgQzEuNjg3OTIzNTIsMTguNjE5IDEuMzc5LDE4LjMxMDA3NjUgMS4zNzksMTcuOTI5IEwxLjM3OSw1LjUxNyBDMS4zNzksNS4xMzU5MjM1MiAxLjY4NzkyMzUyLDQuODI3IDIuMDY5LDQuODI3IEw5LjY3Nyw0LjgyNyBMMTAuODI2LDMuNDQ4IEwxLjM3OSwzLjQ0OCBDMS4wMTI5MTk2NywzLjQ0OCAwLjY2MTg2MjE5NSwzLjU5MzU2MTIxIDAuNDAzMTkxOTYsMy44NTI2MDY2IEMwLjE0NDUyMTcyNiw0LjExMTY1MTk5IC0wLjAwMDUzMDkzNTkzMyw0LjQ2MjkyMDA2IC0xLjQ1MjQxNjAyZS0wNiw0LjgyOSBMLTEuNDUyNDE2MDJlLTA2LDE4LjYyMiBDLTEuNDUyNDE2MDJlLTA2LDE5LjM4MzYwMDcgMC42MTczOTkzMywyMC4wMDEgMS4zNzksMjAuMDAxIEwxNS4xNzIsMjAuMDAxIEMxNS45MzM2MDA3LDIwLjAwMSAxNi41NTEsMTkuMzgzNjAwNyAxNi41NTEsMTguNjIyIEwxNi41NTEsMTguNjIyIEwxNi41NTEsMTEuMTggQzE2LjE4NzI5MTUsMTIuMDA1NTUwNyAxNS43MjQyMDI0LDEyLjc4MzYzNDUgMTUuMTcyLDEzLjQ5NyBMMTUuMTcyLDEzLjQ5NyBaIiBpZD0iUGF0aF81MSI+PC9wYXRoPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4=`

**Comment by royboy789** [comment]
![Screen Shot 2020-12-18 at 7 33 27 AM](https://user-images.githubusercontent.com/4039786/102615098-59aab880-4103-11eb-93d1-733c9e3689fd.png)


@dimitarangelkov better. thoughts @circuitfive ?

**Comment by circuitfive** [comment]
It's better than the megaphone and we can use it for today, but let's keep the issue open while we prepare something with less detail for this tiny format. I think we should probably remove the interior shapes @dimitarangelkov what do you think?

**Comment by dimitarangelkov** [comment]
Here is the revised small icon. 
<img width="205" alt="Screenshot 2021-02-12 at 13 26 59" src="https://user-images.githubusercontent.com/14825668/107762648-008f8780-6d36-11eb-8d5b-bc9e3733ae49.png">

Branch: https://github.com/cloudsponge/better-sharing-wp/tree/44-Admin-sidebar-icon

**Comment by dimitarangelkov** [comment]
@circuitfive 

![Screenshot 2021-02-18 at 13 24 07](https://user-images.githubusercontent.com/14825668/108350391-d2ee8680-71ec-11eb-9bde-533624f13cbf.png)

**Comment by circuitfive** [comment]
Let's go with the first one (top left). Can you please change it everywhere @dimitarangelkov? #18 #36
