### ISSUE TITLE
AutomateWoo not sending emails with Better Sharing installed

### ISSUE THREAD

**Issue by dangerouse** [cloudsponge/better-sharing-wp#50]
Our customer, Bob demonstrated this bug to me. 

AutomateWoo is sending emails when Better Sharing is disabled, but when Better Sharing is enabled, there is an error shown something like: “please enter an email”.

It makes me think that the plugin is not properly adding the emails from the unified field to the hidden AW fields properly.

Let's ensure that we test this with the newest version of the plugin.

**Comment by royboy789** [comment]
@bszyk - please confirm you fixed this issue & close, if not, please address

**Comment by royboy789** [comment]
@bszyk - just making notes based on our conversation about this.

Check to make sure that the latest updates to WordPress and jQuery did not affect how Better Sharing works with AutomateWoo. 

If it is, swap out the jQuery for vanilla JavaScript

**Comment by royboy789** [comment]
This was fixed.
