### ISSUE TITLE
plugin creates error on fresh WP install

### ISSUE THREAD

**Issue by terminusagency** [cloudsponge/better-sharing-wp#51]
Installed on fresh WP install with no other plugins enabled and got the following:

Fatal error: Uncaught Error: Class 'BetterSharingWP\AddOns\WooWishlists\WooWishlists' not found in /home/terminu3/public_html/bettersharing/wp-content/plugins/better-sharing-1.3.0/BetterSharingWP.php:133 Stack trace: #0 /home/terminu3/public_html/bettersharing/wp-includes/class-wp-hook.php(287): BetterSharingWP\{closure}('') #1 /home/terminu3/public_html/bettersharing/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/terminu3/public_html/bettersharing/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /home/terminu3/public_html/bettersharing/wp-settings.php(557): do_action('init') #4 /home/terminu3/public_html/bettersharing/wp-config.php(92): require_once('/home/terminu3/...') #5 /home/terminu3/public_html/bettersharing/wp-load.php(37): require_once('/home/terminu3/...') #6 /home/terminu3/public_html/bettersharing/wp-admin/admin.php(34): require_once('/home/terminu3/...') #7 /home/terminu3/public_html/bettersharing/wp-admin/plugins.php(10): require_once('/home/terminu3/...') #8 {main} in /home/terminu3/public_html/bettersharing/wp-content/plugins/better-sharing-1.3.0/BetterSharingWP.php on line 133

**Comment by royboy789** [comment]
HI @terminusagency sorry, took a bit longer to get through a few little bugs and the new `1.3.2` version.

here is a link to a zip. let me know if you have any issues setting this one up:
https://www.dropbox.com/s/j5uwjxdbhog6n24/better-sharing-1.3.2.zip?dl=0

These new features will be rolled out with that version once we have a few more good test runs, the PR is here:
https://github.com/cloudsponge/better-sharing-wp/pull/47

**Comment by royboy789** [comment]
Hi @terminusagency - A new zip for you for `1.3.3` please let me know if you are still seeing issues.

https://www.dropbox.com/s/3mmcujts21scsux/better-sharing-1.3.3.zip?dl=0
