### ISSUE TITLE
Design Issue: Confusing Add On Menu Page

### ISSUE THREAD

**Issue by royboy789** [cloudsponge/better-sharing-wp#52]
- Text is not clear when plugin is not installed or activated
- Opacity of toggle to 50% might help

**Comment by circuitfive** [comment]
This ticket is referring to this interface:

![image](https://user-images.githubusercontent.com/2659746/106036117-bf3a7f00-6089-11eb-9109-1a07d4ec7c09.png)

**Comment by circuitfive** [comment]
@royboy789 here's a draft of a new design for discussion, we can break it up in several separate issues so that we don't create an oversized project out of it.

![Better Sharing WP AddOns Menu](https://user-images.githubusercontent.com/2659746/106044344-79cf7f00-6094-11eb-9e3a-1a013ad4d2db.png)

**Comment by circuitfive** [comment]
@dimitarangelkov maybe this is a good area for you to be involved in the development tasks?

**Comment by royboy789** [comment]
@circuitfive what if the plugin has both a learn more and a settings?

**Comment by royboy789** [comment]
The Sort order should be broken out into another ticket.

**Comment by circuitfive** [comment]
> @circuitfive what if the plugin has both a learn more and a settings?

We could sneak in the learn more link for the first two as well. Maybe it could get demoted to a hyperlink at the end of the description so it's less prominent.

**Comment by royboy789** [comment]
@circuitfive if you are sending people to a landing page for the plugin, keep it a button. 

Maybe 50/50 width on the 2 buttons? does that look good?

**Comment by circuitfive** [comment]
Ok.

![Better Sharing WP AddOns Menu](https://user-images.githubusercontent.com/2659746/106053279-7b527480-609f-11eb-80e8-009b5b475d01.png)

**Comment by royboy789** [comment]
This is in the PR for `1.3.2` - 
https://github.com/cloudsponge/better-sharing-wp/pull/47

**Comment by circuitfive** [comment]
@royboy789 I made a lander for this so those Learn More buttons can go somewhere useful:

https://www.cloudsponge.com/better-sharing/

There's also some text that you can use for the AddOn descriptions, here it is again for your convenience:

1. AutomateWoo’s Refer A Friend add-on – Rather than forcing users to manually type up to 5 email addresses into separate text fields, Better Sharing modifies this interface to allow a comma-separated list of email addresses with a preview of the subject and body, as well as an optional contact picker so that users never have to type anything manually.
2. WooCommerce  Wishlists – Override the wishlist’s “mailto” link with a beautiful modal dialog for sharing via email with a message preview and contact picker.
3. Coupon Referral Program – Let your users easily copy their coupon link to their clipboard or share it via email with a message preview and contact picker.

Also, it appears that some logic is wrong with the AutomateWoo AddOn since I'm seeing the "Settings" button even though the plugin is not installed.

**Comment by circuitfive** [comment]
@royboy789 with the latest commit we moved away from using standard/default WordPress styles to a custom one that isn't consistent with our own Settings page or the rest of WP Admin. Can we switch back to default styles please?

**Comment by circuitfive** [comment]
I realize now that perhaps you (or Brian) interpreted my wireframe above as a pixel-perfect mockup. That was not my intention, I was just quickly trying to put something together to illustrate the page layout and did not intend to prescribe corner radiuses, fonts, colors, etc.

**Comment by royboy789** [comment]
@circuitfive you are correct, and now that I understand that, we will go ahead and make the design more cohesive.

**Comment by dimitarangelkov** [comment]
![Screenshot 2021-02-03 at 15 04 29](https://user-images.githubusercontent.com/14825668/106750906-254a7780-6631-11eb-99a8-aece591fc648.png)

This is how the fresh v1.3.2 install AddOns page looks like.

I have a couple of comments:
1. The toggle next to `Plugin is not installed or activated` is a bit confusing. Better to display the message without toggle and have the toggle once the related plugin is functional.

2. We can Add the WooCommerce logo on top of each plugin card, also AutomateWoo has its own logo, so we can use it. This will add some visual confidence to the users.

3. Better to have only `Settings` as button, that will appear for the functional plugins. 

4. In my opinion `Learn more` should be text link part of the plugin description content. This way will have visual separation of the presentation on top (Title, Description, Read more) and the configuration at the bottom (Settings + Enable/Disable)

@circuitfive if you want we can mockup something to make it a bit more sexy.

Off topic: @royboy789 it seems the plugin require minimum PHP version 7.4. Is there any specific reason for that? A lot of wordpress websites are still running older versions.

**Comment by royboy789** [comment]
@dimitarangelkov No, not sure if anything in there is 7.4 specific. We can setup some testing environments on older versions to see if anything breaks.

**Comment by royboy789** [comment]
@dimitarangelkov - should add that happy to look at a new mock, we are still testing. @bszyk got blocked most of yesterday with permission issues, but he is currently testing functionality, we can circle back to design once any other small bugs are found and fixed.

**Comment by circuitfive** [comment]
@dimitarangelkov go ahead and take a pass at coding it, your ideas are fine with me, we don't need to see mockups if you're doing the work yourself.

One thing to consider is that we're going to be doing mostly WooCommerce related AddOns so you might end up repeating the same logo a lot, and some of our AddOns might not have a relevant logo to use, so they'll need to look nice too. If you want to leave that one out, it's fine with me.

Please note that a draft of the text that's supposed to go in these boxes is in this issue [☝️](https://github.com/cloudsponge/better-sharing-wp/issues/52#issuecomment-771233411) .

**Comment by dimitarangelkov** [comment]
![1](https://user-images.githubusercontent.com/14825668/108544354-01548a80-72ef-11eb-9450-7b93a4f36766.png)
![2](https://user-images.githubusercontent.com/14825668/108544364-044f7b00-72ef-11eb-9364-b55286ceee23.png)
![3](https://user-images.githubusercontent.com/14825668/108544380-09142f00-72ef-11eb-813f-47287927efd1.png)

Branch https://github.com/cloudsponge/better-sharing-wp/tree/52-addons-page-template-tweaks

@royboy789 You'll notice there is images folder under each `Add-on` assets folder. Would be great if we can get URI to these folders so we can display the images in the UI. These are logos, probably in the future something else add-on specific.

**Comment by dimitarangelkov** [comment]
Based on today's feedback

![4](https://user-images.githubusercontent.com/14825668/108547324-ff8cc600-72f2-11eb-95de-2ea4aed69eb1.png)
![5](https://user-images.githubusercontent.com/14825668/108547333-03204d00-72f3-11eb-900c-b9550aa4f007.png)

**Comment by dimitarangelkov** [comment]
Regarding the `Settings` available for `disabled` add-on. Currently `Settings` are available only when the add-on is activated, if you want this change @royboy789 will have to update the add on classes. Since this is out of the redesign scope I'll leave it to him.

**Comment by circuitfive** [comment]
LGTM @dimitarangelkov go ahead and create a PR whenever you're ready. I moved your last request into a new issue #74.
