### ISSUE TITLE
Create screencast of WP.org deploy process

### ISSUE THREAD

**Issue by dangerouse** [cloudsponge/better-sharing-wp#67]

**Comment by royboy789** [comment]
Related: https://github.com/cloudsponge/better-sharing-wp/issues/49

**Comment by royboy789** [comment]
https://www.dropbox.com/s/9isugy5rzcyuszk/BSWP-build.mov

**Comment by circuitfive** [comment]
This issue cannot be closed yet because the video is incomplete.

**Comment by circuitfive** [comment]
WIP: https://www.loom.com/share/ed6e39a6d60d4b4a9d2cb9e86c97aadc
