### ISSUE TITLE
autoload.php error

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#68]
```
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/terminu3/public_html/bettersharing/wp-content/plugins/better-sharing/BetterSharingWP.php on line 26

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/php74/pear') in /home/terminu3/public_html/bettersharing/wp-content/plugins/better-sharing/BetterSharingWP.php on line 26
```

Reported by @terminusagency after trying to install 1.3.4 from wordpress.org in two different environments/hosts.

**Comment by dangerouse** [comment]
I can confirm that I got the same error when attempting to Activate the Better Sharing plugin. I used Lando to set up a brand new WP instance with:
* PHP: 7.4
* WordPress: 5.7 Beta 3
* WooCommerce: 5.0.0
* Better Sharing: 1.3.4

![image](https://user-images.githubusercontent.com/152403/108575526-613b3900-72cf-11eb-8579-0538dad0a977.png)

**Comment by royboy789** [comment]
Tried fixing this issue by adding the `vendor` directory, but had a permissions issue.
I thought it may have been an issue with no version changes (happened to me in the past), but that did not solve it.

Master is now at 1.3.5 and ready for a retry, @dangerouse if you could retry what we did, making sure `vendor` makes it into trunk. Thinking back at it, we skipped that step after `npm install` to do the `composer install`

**Comment by royboy789** [comment]
This was fixed.

**Comment by dangerouse** [comment]
@royboy789 I just caught up on your comment about missing the `composer install` step. I'd like to add this step to the build but I have a question: 
Does it matter if the `composer.lock` file is present for us since we don't reference any external dependencies/versions?
